spring:
  application:
    name: api-gateway
  gateway:
    httpclient:
      wiretap: true
    httpserver:
      wiretap: true

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        - id: favorite-service
          uri: lb://favorite-service
          predicates:
            - Path=/favorite-service/**
          filters:
            - StripPrefix=1

        - id: authUser-service
          uri: lb://authUser-service
          predicates:
            - Path=/authUser-service/**
          filters:
            - StripPrefix=1

        - id: element-service
          uri: lb://element-service
          predicates:
            - Path=/element-service/**
          filters:
            - StripPrefix=1

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review-service/**
          filters:
            - StripPrefix=1

server:
  port: ${PORT:9000}

eureka:
  client:
    service-url:
      defaultZone: https://dianshomework-eureka.up.railway.app/eureka

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
        web: DEBUG