spring:
  application:
    name: api-gateway
  gateway:
    httpclient:
      wiretap: true
    httpserver:
      wiretap: true

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: https://foolish-development-users.up.railway.app
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: element-service
          uri: https://boss-throne-element.up.railway.app
          predicates:
            - Path=/element-service/**
          filters:
            - StripPrefix=1

        - id: review-service
          uri: https://deafening-drain-reviews.up.railway.app
          predicates:
            - Path=/review-service/**
          filters:
            - StripPrefix=1

        - id: favorite-service
          uri: https://misty-religion-favorite.up.railway.app
          predicates:
            - Path=/favorite-service/**
          filters:
            - StripPrefix=1

server:
  port: ${PORT:9000}

eureka:
  client:
    service-url:
      defaultZone: https://dianshomework-eureka.up.railway.app/eureka

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
        web: DEBUG
